#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Mail-Ezmlm-Archive
version:      0.15
version_from: Archive.pm
installdirs:  site
requires:

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.12
